# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NzNiMzFiMjM4ODBiNThhYzg1ZTBiODFiZGVkODZkOTdjYjE3N2YxNjU0ZTY5YTc5ZDIxNjZlNGYxZmQ5YmU1OTdkZTRmY2JhODRjNmMwZmUyNDFhY2ZkZjY1M2ZiYWEzODU5NzkwMDNiNDViOTkzZGRkOWRkMjljZjA3NWE5NTA=
