package com.edu.sena.zentry.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AdministradorConjuntoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdministradorConjuntoAllPropertiesEquals(AdministradorConjunto expected, AdministradorConjunto actual) {
        assertAdministradorConjuntoAutoGeneratedPropertiesEquals(expected, actual);
        assertAdministradorConjuntoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdministradorConjuntoAllUpdatablePropertiesEquals(
        AdministradorConjunto expected,
        AdministradorConjunto actual
    ) {
        assertAdministradorConjuntoUpdatableFieldsEquals(expected, actual);
        assertAdministradorConjuntoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdministradorConjuntoAutoGeneratedPropertiesEquals(
        AdministradorConjunto expected,
        AdministradorConjunto actual
    ) {
        assertThat(actual)
            .as("Verify AdministradorConjunto auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdministradorConjuntoUpdatableFieldsEquals(AdministradorConjunto expected, AdministradorConjunto actual) {
        assertThat(actual)
            .as("Verify AdministradorConjunto relevant properties")
            .satisfies(a -> assertThat(a.getNombres()).as("check nombres").isEqualTo(expected.getNombres()))
            .satisfies(a -> assertThat(a.getApellidos()).as("check apellidos").isEqualTo(expected.getApellidos()))
            .satisfies(a -> assertThat(a.getNumeroDocumento()).as("check numeroDocumento").isEqualTo(expected.getNumeroDocumento()))
            .satisfies(a -> assertThat(a.getTelefono()).as("check telefono").isEqualTo(expected.getTelefono()))
            .satisfies(a -> assertThat(a.getCorreo()).as("check correo").isEqualTo(expected.getCorreo()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdministradorConjuntoUpdatableRelationshipsEquals(
        AdministradorConjunto expected,
        AdministradorConjunto actual
    ) {
        assertThat(actual)
            .as("Verify AdministradorConjunto relationships")
            .satisfies(a ->
                assertThat(a.getConjuntoResidencial()).as("check conjuntoResidencial").isEqualTo(expected.getConjuntoResidencial())
            )
            .satisfies(a -> assertThat(a.getTipoDocumento()).as("check tipoDocumento").isEqualTo(expected.getTipoDocumento()));
    }
}
