package com.edu.sena.zentry.domain;

import static com.edu.sena.zentry.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class AnunciosAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnunciosAllPropertiesEquals(Anuncios expected, Anuncios actual) {
        assertAnunciosAutoGeneratedPropertiesEquals(expected, actual);
        assertAnunciosAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnunciosAllUpdatablePropertiesEquals(Anuncios expected, Anuncios actual) {
        assertAnunciosUpdatableFieldsEquals(expected, actual);
        assertAnunciosUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnunciosAutoGeneratedPropertiesEquals(Anuncios expected, Anuncios actual) {
        assertThat(actual)
            .as("Verify Anuncios auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnunciosUpdatableFieldsEquals(Anuncios expected, Anuncios actual) {
        assertThat(actual)
            .as("Verify Anuncios relevant properties")
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a ->
                assertThat(a.getFecha()).as("check fecha").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.getFecha())
            )
            .satisfies(a -> assertThat(a.getImagen()).as("check imagen").isEqualTo(expected.getImagen()))
            .satisfies(a ->
                assertThat(a.getImagenContentType()).as("check imagen content type").isEqualTo(expected.getImagenContentType())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnunciosUpdatableRelationshipsEquals(Anuncios expected, Anuncios actual) {
        assertThat(actual)
            .as("Verify Anuncios relationships")
            .satisfies(a ->
                assertThat(a.getConjuntoResidencial()).as("check conjuntoResidencial").isEqualTo(expected.getConjuntoResidencial())
            )
            .satisfies(a ->
                assertThat(a.getAdministradorConjunto()).as("check administradorConjunto").isEqualTo(expected.getAdministradorConjunto())
            );
    }
}
