package com.edu.sena.zentry.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConjuntoResidencialAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConjuntoResidencialAllPropertiesEquals(ConjuntoResidencial expected, ConjuntoResidencial actual) {
        assertConjuntoResidencialAutoGeneratedPropertiesEquals(expected, actual);
        assertConjuntoResidencialAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConjuntoResidencialAllUpdatablePropertiesEquals(ConjuntoResidencial expected, ConjuntoResidencial actual) {
        assertConjuntoResidencialUpdatableFieldsEquals(expected, actual);
        assertConjuntoResidencialUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConjuntoResidencialAutoGeneratedPropertiesEquals(ConjuntoResidencial expected, ConjuntoResidencial actual) {
        assertThat(actual)
            .as("Verify ConjuntoResidencial auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConjuntoResidencialUpdatableFieldsEquals(ConjuntoResidencial expected, ConjuntoResidencial actual) {
        assertThat(actual)
            .as("Verify ConjuntoResidencial relevant properties")
            .satisfies(a -> assertThat(a.getNombreConjunto()).as("check nombreConjunto").isEqualTo(expected.getNombreConjunto()))
            .satisfies(a -> assertThat(a.getDireccionConjunto()).as("check direccionConjunto").isEqualTo(expected.getDireccionConjunto()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConjuntoResidencialUpdatableRelationshipsEquals(ConjuntoResidencial expected, ConjuntoResidencial actual) {
        // empty method
    }
}
