package com.edu.sena.zentry.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FacturaDePagoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacturaDePagoAllPropertiesEquals(FacturaDePago expected, FacturaDePago actual) {
        assertFacturaDePagoAutoGeneratedPropertiesEquals(expected, actual);
        assertFacturaDePagoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacturaDePagoAllUpdatablePropertiesEquals(FacturaDePago expected, FacturaDePago actual) {
        assertFacturaDePagoUpdatableFieldsEquals(expected, actual);
        assertFacturaDePagoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacturaDePagoAutoGeneratedPropertiesEquals(FacturaDePago expected, FacturaDePago actual) {
        assertThat(actual)
            .as("Verify FacturaDePago auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacturaDePagoUpdatableFieldsEquals(FacturaDePago expected, FacturaDePago actual) {
        assertThat(actual)
            .as("Verify FacturaDePago relevant properties")
            .satisfies(a -> assertThat(a.getFechaEnvio()).as("check fechaEnvio").isEqualTo(expected.getFechaEnvio()))
            .satisfies(a -> assertThat(a.getImagenFactura()).as("check imagenFactura").isEqualTo(expected.getImagenFactura()))
            .satisfies(a ->
                assertThat(a.getImagenFacturaContentType())
                    .as("check imagenFactura content type")
                    .isEqualTo(expected.getImagenFacturaContentType())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacturaDePagoUpdatableRelationshipsEquals(FacturaDePago expected, FacturaDePago actual) {
        assertThat(actual)
            .as("Verify FacturaDePago relationships")
            .satisfies(a ->
                assertThat(a.getConjuntoResidencial()).as("check conjuntoResidencial").isEqualTo(expected.getConjuntoResidencial())
            )
            .satisfies(a -> assertThat(a.getVinculado()).as("check vinculado").isEqualTo(expected.getVinculado()));
    }
}
