package com.edu.sena.zentry.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InmuebleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInmuebleAllPropertiesEquals(Inmueble expected, Inmueble actual) {
        assertInmuebleAutoGeneratedPropertiesEquals(expected, actual);
        assertInmuebleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInmuebleAllUpdatablePropertiesEquals(Inmueble expected, Inmueble actual) {
        assertInmuebleUpdatableFieldsEquals(expected, actual);
        assertInmuebleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInmuebleAutoGeneratedPropertiesEquals(Inmueble expected, Inmueble actual) {
        assertThat(actual)
            .as("Verify Inmueble auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInmuebleUpdatableFieldsEquals(Inmueble expected, Inmueble actual) {
        assertThat(actual)
            .as("Verify Inmueble relevant properties")
            .satisfies(a -> assertThat(a.getTipoInmueble()).as("check tipoInmueble").isEqualTo(expected.getTipoInmueble()))
            .satisfies(a -> assertThat(a.getTorre()).as("check torre").isEqualTo(expected.getTorre()))
            .satisfies(a -> assertThat(a.getNumeroInmueble()).as("check numeroInmueble").isEqualTo(expected.getNumeroInmueble()))
            .satisfies(a -> assertThat(a.getPiso()).as("check piso").isEqualTo(expected.getPiso()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInmuebleUpdatableRelationshipsEquals(Inmueble expected, Inmueble actual) {
        assertThat(actual)
            .as("Verify Inmueble relationships")
            .satisfies(a ->
                assertThat(a.getConjuntoResidencial()).as("check conjuntoResidencial").isEqualTo(expected.getConjuntoResidencial())
            );
    }
}
