package com.edu.sena.zentry.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReservasAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservasAllPropertiesEquals(Reservas expected, Reservas actual) {
        assertReservasAutoGeneratedPropertiesEquals(expected, actual);
        assertReservasAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservasAllUpdatablePropertiesEquals(Reservas expected, Reservas actual) {
        assertReservasUpdatableFieldsEquals(expected, actual);
        assertReservasUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservasAutoGeneratedPropertiesEquals(Reservas expected, Reservas actual) {
        assertThat(actual)
            .as("Verify Reservas auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservasUpdatableFieldsEquals(Reservas expected, Reservas actual) {
        assertThat(actual)
            .as("Verify Reservas relevant properties")
            .satisfies(a -> assertThat(a.getFechaSolicitud()).as("check fechaSolicitud").isEqualTo(expected.getFechaSolicitud()))
            .satisfies(a -> assertThat(a.getFechaReserva()).as("check fechaReserva").isEqualTo(expected.getFechaReserva()))
            .satisfies(a -> assertThat(a.getHoraInicio()).as("check horaInicio").isEqualTo(expected.getHoraInicio()))
            .satisfies(a -> assertThat(a.getHorafin()).as("check horafin").isEqualTo(expected.getHorafin()))
            .satisfies(a -> assertThat(a.getCuposApartados()).as("check cuposApartados").isEqualTo(expected.getCuposApartados()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservasUpdatableRelationshipsEquals(Reservas expected, Reservas actual) {
        assertThat(actual)
            .as("Verify Reservas relationships")
            .satisfies(a -> assertThat(a.getServicioConjunto()).as("check servicioConjunto").isEqualTo(expected.getServicioConjunto()))
            .satisfies(a -> assertThat(a.getVinculado()).as("check vinculado").isEqualTo(expected.getVinculado()));
    }
}
