package com.edu.sena.zentry.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ServicioConjuntoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioConjuntoAllPropertiesEquals(ServicioConjunto expected, ServicioConjunto actual) {
        assertServicioConjuntoAutoGeneratedPropertiesEquals(expected, actual);
        assertServicioConjuntoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioConjuntoAllUpdatablePropertiesEquals(ServicioConjunto expected, ServicioConjunto actual) {
        assertServicioConjuntoUpdatableFieldsEquals(expected, actual);
        assertServicioConjuntoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioConjuntoAutoGeneratedPropertiesEquals(ServicioConjunto expected, ServicioConjunto actual) {
        assertThat(actual)
            .as("Verify ServicioConjunto auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioConjuntoUpdatableFieldsEquals(ServicioConjunto expected, ServicioConjunto actual) {
        assertThat(actual)
            .as("Verify ServicioConjunto relevant properties")
            .satisfies(a -> assertThat(a.getDisponible()).as("check disponible").isEqualTo(expected.getDisponible()))
            .satisfies(a -> assertThat(a.getAforoMaximo()).as("check aforoMaximo").isEqualTo(expected.getAforoMaximo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioConjuntoUpdatableRelationshipsEquals(ServicioConjunto expected, ServicioConjunto actual) {
        assertThat(actual)
            .as("Verify ServicioConjunto relationships")
            .satisfies(a ->
                assertThat(a.getConjuntoResidencial()).as("check conjuntoResidencial").isEqualTo(expected.getConjuntoResidencial())
            )
            .satisfies(a -> assertThat(a.getServicio()).as("check servicio").isEqualTo(expected.getServicio()));
    }
}
