package com.edu.sena.zentry.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ServicioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioAllPropertiesEquals(Servicio expected, Servicio actual) {
        assertServicioAutoGeneratedPropertiesEquals(expected, actual);
        assertServicioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioAllUpdatablePropertiesEquals(Servicio expected, Servicio actual) {
        assertServicioUpdatableFieldsEquals(expected, actual);
        assertServicioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioAutoGeneratedPropertiesEquals(Servicio expected, Servicio actual) {
        assertThat(actual)
            .as("Verify Servicio auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioUpdatableFieldsEquals(Servicio expected, Servicio actual) {
        assertThat(actual)
            .as("Verify Servicio relevant properties")
            .satisfies(a -> assertThat(a.getDisponibilidad()).as("check disponibilidad").isEqualTo(expected.getDisponibilidad()))
            .satisfies(a -> assertThat(a.getNombreZonaComun()).as("check nombreZonaComun").isEqualTo(expected.getNombreZonaComun()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioUpdatableRelationshipsEquals(Servicio expected, Servicio actual) {
        // empty method
    }
}
