package com.edu.sena.zentry.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoDocumentoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDocumentoAllPropertiesEquals(TipoDocumento expected, TipoDocumento actual) {
        assertTipoDocumentoAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoDocumentoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDocumentoAllUpdatablePropertiesEquals(TipoDocumento expected, TipoDocumento actual) {
        assertTipoDocumentoUpdatableFieldsEquals(expected, actual);
        assertTipoDocumentoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDocumentoAutoGeneratedPropertiesEquals(TipoDocumento expected, TipoDocumento actual) {
        assertThat(actual)
            .as("Verify TipoDocumento auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDocumentoUpdatableFieldsEquals(TipoDocumento expected, TipoDocumento actual) {
        assertThat(actual)
            .as("Verify TipoDocumento relevant properties")
            .satisfies(a ->
                assertThat(a.getNombreTipoDocumento()).as("check nombreTipoDocumento").isEqualTo(expected.getNombreTipoDocumento())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDocumentoUpdatableRelationshipsEquals(TipoDocumento expected, TipoDocumento actual) {
        // empty method
    }
}
