package com.edu.sena.zentry.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VinculadoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVinculadoAllPropertiesEquals(Vinculado expected, Vinculado actual) {
        assertVinculadoAutoGeneratedPropertiesEquals(expected, actual);
        assertVinculadoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVinculadoAllUpdatablePropertiesEquals(Vinculado expected, Vinculado actual) {
        assertVinculadoUpdatableFieldsEquals(expected, actual);
        assertVinculadoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVinculadoAutoGeneratedPropertiesEquals(Vinculado expected, Vinculado actual) {
        assertThat(actual)
            .as("Verify Vinculado auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVinculadoUpdatableFieldsEquals(Vinculado expected, Vinculado actual) {
        assertThat(actual)
            .as("Verify Vinculado relevant properties")
            .satisfies(a -> assertThat(a.getNombres()).as("check nombres").isEqualTo(expected.getNombres()))
            .satisfies(a -> assertThat(a.getApellidos()).as("check apellidos").isEqualTo(expected.getApellidos()))
            .satisfies(a -> assertThat(a.getNumeroDocumento()).as("check numeroDocumento").isEqualTo(expected.getNumeroDocumento()))
            .satisfies(a -> assertThat(a.getTelefono()).as("check telefono").isEqualTo(expected.getTelefono()))
            .satisfies(a -> assertThat(a.getCorreo()).as("check correo").isEqualTo(expected.getCorreo()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVinculadoUpdatableRelationshipsEquals(Vinculado expected, Vinculado actual) {
        assertThat(actual)
            .as("Verify Vinculado relationships")
            .satisfies(a -> assertThat(a.getTipoDocumento()).as("check tipoDocumento").isEqualTo(expected.getTipoDocumento()))
            .satisfies(a ->
                assertThat(a.getAdministradorConjunto()).as("check administradorConjunto").isEqualTo(expected.getAdministradorConjunto())
            );
    }
}
