package com.edu.sena.zentry.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VinculadoInmuebleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVinculadoInmuebleAllPropertiesEquals(VinculadoInmueble expected, VinculadoInmueble actual) {
        assertVinculadoInmuebleAutoGeneratedPropertiesEquals(expected, actual);
        assertVinculadoInmuebleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVinculadoInmuebleAllUpdatablePropertiesEquals(VinculadoInmueble expected, VinculadoInmueble actual) {
        assertVinculadoInmuebleUpdatableFieldsEquals(expected, actual);
        assertVinculadoInmuebleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVinculadoInmuebleAutoGeneratedPropertiesEquals(VinculadoInmueble expected, VinculadoInmueble actual) {
        assertThat(actual)
            .as("Verify VinculadoInmueble auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVinculadoInmuebleUpdatableFieldsEquals(VinculadoInmueble expected, VinculadoInmueble actual) {
        assertThat(actual)
            .as("Verify VinculadoInmueble relevant properties")
            .satisfies(a -> assertThat(a.getTipoVinculo()).as("check tipoVinculo").isEqualTo(expected.getTipoVinculo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVinculadoInmuebleUpdatableRelationshipsEquals(VinculadoInmueble expected, VinculadoInmueble actual) {
        assertThat(actual)
            .as("Verify VinculadoInmueble relationships")
            .satisfies(a -> assertThat(a.getVinculado()).as("check vinculado").isEqualTo(expected.getVinculado()))
            .satisfies(a -> assertThat(a.getInmueble()).as("check inmueble").isEqualTo(expected.getInmueble()));
    }
}
